# 异常处理

Python 有两种错误很容易辨认： **语法错误** 和 **异常** 。

Python assert（断言）用于判断一个表达式，在表达式条件为 false 的时候触发异常。

## 语法错误

Python 的语法错误或者称之为解析错，是初学者经常碰到的，如下实例

```py
>>>while True print('Hello world')
  File "<stdin>", line 1, in ?
    while True print('Hello world')
                   ^
SyntaxError: invalid syntax
```

这个例子中，函数 print() 被检查到有错误，是它前面缺少了一个冒号 : 。

语法分析器指出了出错的一行，并且在最先找到的错误的位置标记了一个小小的箭头。

## 异常

即便 Python 程序的语法是正确的，在运行它的时候，也有可能发生错误。运行期检测到的错误被称为异常。

大多数的异常都不会被程序处理，都以错误信息的形式展现在这里:

```py
>>>10 * (1/0)             # 0 不能作为除数，触发异常
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
ZeroDivisionError: division by zero
>>> 4 + spam*3             # spam 未定义，触发异常
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
NameError: name 'spam' is not defined
>>> '2' + 2               # int 不能与 str 相加，触发异常
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
TypeError: Can't convert 'int' object to str implicitly
```

异常以不同的类型出现，这些类型都作为信息的一部分打印出来: 例子中的类型有 ZeroDivisionError，NameError 和 TypeError。

错误信息的前面部分显示了异常发生的上下文，并以调用栈的形式显示具体信息。

## 异常处理

![异常处理](https://www.runoob.com/wp-content/uploads/2019/07/try_except_else_finally.png)

python中使用try/except/finally关键字处理异常.

语法格式：

```py
try:
	代码
except 异常类型1:
	处理	
except 异常类型2:
	处理	
finally:
	代码（没有异常）
```

基础示例：

```py
path = "c:\pytest.txt"
try:
    fi = open(path)
    try:
        fi.read()
    finally:
        fi.close()
        print("最后都会执行")
except FileNotFoundError:
    print("找不到相应的文件")
except IOError:
    print("文件操作失败IOError")
```

## 抛出异常

Python 使用 raise 语句抛出一个指定的异常。

raise语法格式如下：

`raise [Exception [, args [, traceback]]]`

以下实例如果 x 大于 5 就触发异常:

```py
x = 10
if x > 5:
    raise Exception('x 不能大于 5。x 的值为: {}'.format(x))
```

执行以上代码会触发异常：

```bash
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    raise Exception('x 不能大于 5。x 的值为: {}'.format(x))
Exception: x 不能大于 5。x 的值为: 10
```

raise 唯一的一个参数指定了要被抛出的异常。它必须是一个异常的实例或者是异常的类（也就是 Exception 的子类）。

如果你只想知道这是否抛出了一个异常，并不想去处理它，那么一个简单的 raise 语句就可以再次把它抛出。

```py
>>>try:
        raise NameError('HiThere')
    except NameError:
        print('An exception flew by!')
        raise
   
An exception flew by!
Traceback (most recent call last):
  File "<stdin>", line 2, in ?
NameError: HiThere
```

## 用户自定义异常

详见：https://www.runoob.com/python3/python3-errors-execptions.html

## 异常类型

<details>
<summary>表格</summary>

Name | 描述
-|-
BaseException	| 所有异常的基类
SystemExit	| 解释器请求退出
KeyboardInterrupt	| 用户中断执行(通常是输入^C)
Exception	| 常规错误的基类
StopIteration	| 迭代器没有更多的值
GeneratorExit	| 生成器(generator)发生异常来通知退出
StandardError	| 所有的内建标准异常的基类
ArithmeticError	| 所有数值计算错误的基类
FloatingPointError	| 浮点计算错误
OverflowError	| 数值运算超出最大限制
ZeroDivisionError	| 除(或取模)零 (所有数据类型)
AssertionError	| 断言语句失败
AttributeError	| 对象没有这个属性
EOFError	| 没有内建输入,到达EOF 标记
EnvironmentError	| 操作系统错误的基类
IOError	| 输入/输出操作失败
OSError	| 操作系统错误
WindowsError	| 系统调用失败
ImportError	| 导入模块/对象失败
LookupError	| 无效数据查询的基类
IndexError	| 序列中没有此索引(index)
KeyError	| 映射中没有这个键
MemoryError	| 内存溢出错误(对于Python 解释器不是致命的)
NameError	| 未声明/初始化对象 (没有属性)
UnboundLocalError	| 访问未初始化的本地变量
ReferenceError	| 弱引用(Weak reference)试图访问已经垃圾回收了的对象
RuntimeError	| 一般的运行时错误
NotImplementedError	| 尚未实现的方法
SyntaxError	| Python 语法错误
IndentationError	| 缩进错误
TabError	| Tab 和空格混用
SystemError	| 一般的解释器系统错误
TypeError	| 对类型无效的操作
ValueError	| 传入无效的参数
UnicodeError	| Unicode 相关的错误
UnicodeDecodeError	| Unicode 解码时的错误
UnicodeEncodeError	| Unicode 编码时错误
UnicodeTranslateError	| Unicode 转换时错误
Warning	| 警告的基类
DeprecationWarning	| 关于被弃用的特征的警告
FutureWarning	| 关于构造将来语义会有改变的警告
OverflowWarning	| 旧的关于自动提升为长整型(long)的警告
PendingDeprecationWarning	| 关于特性将会被废弃的警告
RuntimeWarning	| 可疑的运行时行为(runtime behavior)的警告
SyntaxWarning	| 可疑的语法的警告
UserWarning	| 用户代码生成的警告
</details>

---

下一节：[垃圾回收gc](./垃圾回收gc.md)